### PR TITLE
Add data

### PR DESCRIPTION
**Pull request by shweta-7span**

### CODE REVIEW

**Comment by nnaeyes6** [comment]
this is the pull request @Gaurangseven. please kindly merge

**Comment by Gaurangseven** [comment]
Kindly add Social handles into the List ,atleast one is mandatory,Thanks

**Comment by nnaeyes6** [comment]
My GitHub and twitter handles are there boss

**Comment by Gaurangseven** [comment]
I was saying to @shweta-7span

**Pull request closed without merging**
