### PR TITLE
Feature new data

### PR DESCRIPTION
**Pull request by shweta-7span**

### CODE REVIEW

**Comment by Gaurangseven** [comment]
already i have merged you PR ,not sure what you are trying to do, kindly connect via twitter to resolve your issue ,Thanks

**Comment by shweta-7span** [comment]
Ohh sorry. I thought that the PR was rejected. Thanks.

**Comment by Gaurangseven** [comment]
I hope its showing in your hacktoberfest profile .

**Comment by shweta-7span** [comment]
Yes. Thank you.

**Pull request closed without merging**
